title: Subodh's Ruminations
logo: /assets/logo.jpg
description: A collection of posts on (bio)statistics and whatever else comes up
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author: Subodh Selukar
